from __future__ import annotations

import copy
import hashlib
import importlib
import json
import socket
import time
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import Mock

import pytest
from quant_platform_kit.risk.contracts import CandidateRiskIdentity
from quant_platform_kit.risk.contracts import RiskAction
from quant_platform_kit.strategy_lifecycle.contracts import BacktestResult
from quant_platform_kit.strategy_lifecycle.backtest_orchestrator import PromotionBacktestRunner

from test_soxl_pit_input_packager import _binding, _raw_sessions, _source_contract
from us_equity_snapshot_pipelines.lifecycle import soxl_pit_input_packager as packager


SOURCE_UES_REVISION = "15df2a42df5d230cfb03a7cb655fd4b226956681"
SOURCE_QPK_REVISION = "730ad9f3983bd90cd75adecb67fcf483ffb96736"
RUNTIME_UES_REVISION = "33d8c09a9aa517cde94f36d2f67e526c340ea6e9"
NOW = datetime(2026, 9, 9, 8, tzinfo=UTC)


@pytest.fixture(autouse=True)
def no_network(monkeypatch):
    def blocked(*_args, **_kwargs):
        raise AssertionError("network is forbidden")

    monkeypatch.setattr(socket.socket, "connect", blocked)
    monkeypatch.setattr(socket, "create_connection", blocked)


def _module():
    return importlib.import_module("us_equity_snapshot_pipelines.lifecycle.soxl_isolated_research")


@pytest.fixture(scope="module")
def synthetic_package(tmp_path_factory):
    # These prices are generated by the existing synthetic fixture. Provider-shaped
    # metadata exercises the production validator; no real source rows are read.
    rows = _raw_sessions()
    source = _source_contract(rows)
    source["data_class"] = "provider_observed"
    for item in source["logical_inputs"]:
        item.update(
            data_origin="provider_observed", provider_id="fixture-provider",
            provider_instrument_id=f"fixture:{item['logical_input_id']}",
            retention_scope="filevault_local_encrypted_immutable_internal_research_only",
        )
    prepared = packager.prepare_soxl_pit_input(
        rows, source,
        trusted_regime_source_contract_sha256=hashlib.sha256(packager.canonical_json_bytes(source)).hexdigest(),
    )
    binding = _binding(prepared.input_manifest_sha256)
    binding.update(
        strategy_revision=SOURCE_UES_REVISION,
        qpk_revision=SOURCE_QPK_REVISION,
        source_contract_sha256=prepared.source_contract_sha256,
    )
    identity = CandidateRiskIdentity(**{
        key: binding[key] for key in (
            "strategy_profile", "account_mode", "strategy_revision", "runner_revision",
            "config_sha256", "input_manifest_sha256", "authority_receipt_sha256",
        )
    })
    binding["candidate_identity_sha256"] = identity.candidate_sha256
    root = tmp_path_factory.mktemp("generated-soxl-input") / "snapshot"
    packager.publish_soxl_pit_input(prepared, _binding(prepared.input_manifest_sha256) | {
        "source_contract_sha256": prepared.source_contract_sha256,
    }, root)
    files = {path.name: path.read_bytes() for path in root.iterdir()}
    package = json.loads(files["package-manifest.json"])
    package["identity"] = binding
    files["package-manifest.json"] = packager.canonical_json_bytes(package)
    return files


@pytest.fixture
def snapshot(tmp_path, synthetic_package):
    root = tmp_path / "snapshot"
    root.mkdir(mode=0o700)
    for name, data in synthetic_package.items():
        path = root / name
        path.write_bytes(data)
        path.chmod(0o600)
    return root


def _arguments(root):
    package_bytes = (root / "package-manifest.json").read_bytes()
    return {
        "expected_package_sha256": hashlib.sha256(package_bytes).hexdigest(),
        "expected_input_manifest_sha256": json.loads(package_bytes)["input_manifest_sha256"],
    }


def _preflight(root, monkeypatch, **kwargs):
    module = _module()
    monkeypatch.setattr(module, "_now", lambda: NOW)
    return module.preflight_soxl_isolated_research(root, **(_arguments(root) | kwargs))


def test_preflight_returns_original_read_only_reference_and_only_three_bounded_configs(snapshot, monkeypatch):
    from us_equity_strategies.manifests import soxl_soxx_trend_income_manifest

    old_config = copy.deepcopy(soxl_soxx_trend_income_manifest.default_config)
    before = {path.name: (path.read_bytes(), path.stat().st_mode) for path in snapshot.iterdir()}
    ledger = snapshot.parent / "mandate-authority.sqlite3"
    ledger.write_bytes(b"old consumed ledger must stay unchanged")

    result = _preflight(snapshot, monkeypatch)

    assert result["input_path"] == snapshot / "input.json"
    assert result["input_manifest_path"] == snapshot / "input-manifest.json"
    assert result["source_identity"] == json.loads(before["package-manifest.json"][0])["identity"]
    assert result["source_identity"]["strategy_revision"] == SOURCE_UES_REVISION
    assert result["source_identity"]["qpk_revision"] == SOURCE_QPK_REVISION
    assert result["execution_provider"] == "codex"
    assert result["parameter_values"] == (0.08, 0.10, 0.12)
    assert result["max_trials"] == 25
    assert result["learning_only"] is True
    assert result["promotion_eligible"] is False
    assert result["live_ready"] is False
    assert result["size_zero_required"] is True
    assert result["no_order"] is True
    assert result["real_backtest_executed"] is False
    assert len(result["runtime_configs"]) == 3
    for value, config in zip(result["parameter_values"], result["runtime_configs"], strict=True):
        assert config == dict(old_config, trend_entry_buffer=value)
    result["runtime_configs"][1]["managed_symbols"] = ()
    assert result["runtime_configs"][0] == old_config
    assert soxl_soxx_trend_income_manifest.default_config == old_config
    assert _module().UES_REVISION == RUNTIME_UES_REVISION
    assert packager.QPK_REVISION != result["source_identity"]["qpk_revision"]
    assert before == {path.name: (path.read_bytes(), path.stat().st_mode) for path in snapshot.iterdir()}
    assert ledger.read_bytes() == b"old consumed ledger must stay unchanged"


@pytest.mark.parametrize("overrides", [
    {"execution_provider": "cursor"}, {"execution_provider": "api"},
    {"entry_buffers": ()}, {"entry_buffers": (0.10, 0.12)},
    {"entry_buffers": (0.08, 0.079)}, {"entry_buffers": (0.08, 0.121)},
    {"entry_buffers": (0.08, True)}, {"entry_buffers": (0.08, "0.10")},
    {"entry_buffers": (0.08, float("nan"))}, {"entry_buffers": (0.08, float("inf"))},
    {"entry_buffers": (0.08, 10 ** 400)},
    {"entry_buffers": (0.08, 0.08)}, {"entry_buffers": (0.08, 0.12, 0.10)},
    {"entry_buffers": tuple(0.08 + i / 1000 for i in range(26))},
])
def test_invalid_parameters_and_paid_channels_are_rejected_before_input_read(tmp_path, overrides):
    module = _module()
    with pytest.raises(module.SoxlIsolatedResearchError, match="research_request_invalid"):
        module.preflight_soxl_isolated_research(
            tmp_path / "not-read", expected_package_sha256="a" * 64,
            expected_input_manifest_sha256="b" * 64, **overrides,
        )


def test_trial_cap_includes_baseline_and_accepts_exactly_twenty_five(snapshot, monkeypatch):
    values = tuple(0.08 + i / 1000 for i in range(25))
    result = _preflight(snapshot, monkeypatch, entry_buffers=values)
    assert len(result["runtime_configs"]) == 25
    assert result["runtime_configs"][0]["trend_entry_buffer"] == 0.08


@pytest.mark.parametrize("which", ["expected_package_sha256", "expected_input_manifest_sha256"])
def test_trusted_package_and_input_roots_cannot_be_self_attested(snapshot, monkeypatch, which):
    with pytest.raises(_module().SoxlIsolatedResearchError, match="snapshot_invalid"):
        _preflight(snapshot, monkeypatch, **{which: "0" * 64})


@pytest.mark.parametrize("member", ["input.json", "input-manifest.json", "sessions.json"])
def test_member_byte_tampering_is_rejected(snapshot, monkeypatch, member):
    with (snapshot / member).open("ab") as stream:
        stream.write(b" ")
    with pytest.raises(_module().SoxlIsolatedResearchError, match="snapshot_invalid"):
        _preflight(snapshot, monkeypatch)


@pytest.mark.parametrize("change", ["extra", "missing", "symlink", "directory_mode", "member_mode"])
def test_private_package_members_and_modes_are_preserved(snapshot, monkeypatch, change):
    if change == "extra":
        (snapshot / "unexpected.json").write_text("{}")
    elif change == "missing":
        (snapshot / "sessions.json").unlink()
    elif change == "symlink":
        original = snapshot / "sessions.json"
        outside = snapshot.parent / "outside.json"
        original.rename(outside)
        original.symlink_to(outside)
    elif change == "directory_mode":
        snapshot.chmod(0o755)
    else:
        (snapshot / "input.json").chmod(0o644)
    with pytest.raises(_module().SoxlIsolatedResearchError, match="snapshot_invalid"):
        _preflight(snapshot, monkeypatch)


@pytest.mark.parametrize("expiry", ["2026-09-09T08:00:00Z", "2026-09-08T08:00:00Z", "invalid"])
def test_current_retention_not_historical_as_of_controls_read_admission(snapshot, monkeypatch, expiry):
    path = snapshot / "package-manifest.json"
    package = json.loads(path.read_bytes())
    package["source_contract"]["logical_inputs"][0]["retention_expires_at"] = expiry
    path.write_bytes(packager.canonical_json_bytes(package))
    with pytest.raises(_module().SoxlIsolatedResearchError, match="snapshot_invalid"):
        _preflight(snapshot, monkeypatch)


def test_source_validator_failure_is_sanitized(snapshot, monkeypatch):
    module = _module()

    def broken(*_args, **_kwargs):
        raise ValueError("private provider rows and secret must not escape")

    monkeypatch.setattr(packager, "validate_soxl_pit_regime_source_contract", broken)
    with pytest.raises(module.SoxlIsolatedResearchError) as caught:
        _preflight(snapshot, monkeypatch)
    assert str(caught.value) == "snapshot_invalid"
    assert caught.value.__cause__ is None


@pytest.mark.parametrize("change", ["synthetic", "retention_scope", "source_identity", "old_candidate", "dependency"])
def test_original_source_and_candidate_bindings_cannot_be_relabelled(snapshot, monkeypatch, change):
    path = snapshot / "package-manifest.json"
    package = json.loads(path.read_bytes())
    if change == "synthetic":
        package["source_contract"]["data_class"] = "synthetic_fixture"
    elif change == "retention_scope":
        package["source_contract"]["logical_inputs"][0]["retention_scope"] = "unrestricted"
    elif change == "source_identity":
        package["identity"]["source_contract_sha256"] = "0" * 64
    elif change == "old_candidate":
        package["candidate_id"] = "new-research-candidate"
    else:
        package["identity"]["qpk_revision"] = "0" * 40
    path.write_bytes(packager.canonical_json_bytes(package))
    with pytest.raises(_module().SoxlIsolatedResearchError, match="snapshot_invalid"):
        _preflight(snapshot, monkeypatch)


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("strategy_revision", "0" * 40),
        ("qpk_revision", "0" * 40),
        ("candidate_identity_sha256", "0" * 64),
    ],
)
def test_unknown_source_lineage_or_identity_is_rejected(snapshot, monkeypatch, field, value):
    path = snapshot / "package-manifest.json"
    package = json.loads(path.read_bytes())
    package["identity"][field] = value
    path.write_bytes(packager.canonical_json_bytes(package))
    with pytest.raises(_module().SoxlIsolatedResearchError, match="snapshot_invalid"):
        _preflight(snapshot, monkeypatch)


def test_public_publish_still_rejects_source_qpk_revision(tmp_path):
    rows = _raw_sessions()
    prepared = packager.prepare_soxl_pit_input(rows, _source_contract(rows))
    binding = _binding(prepared.input_manifest_sha256)
    binding.update(
        qpk_revision=SOURCE_QPK_REVISION,
        source_contract_sha256=prepared.source_contract_sha256,
    )
    with pytest.raises(packager.SoxlPITPackagerError, match="QPK revision mismatch"):
        packager.publish_soxl_pit_input(prepared, binding, tmp_path / "old-source")


def test_single_parameter_reaches_the_existing_strategy_calculation_without_execution(snapshot, monkeypatch):
    from quant_platform_kit.common.models import PortfolioSnapshot
    from quant_platform_kit.common.strategy_contracts import StrategyContext
    from us_equity_strategies import entrypoints

    def forbidden(*_args, **_kwargs):
        raise AssertionError("execution is forbidden")

    monkeypatch.setattr(entrypoints, "record_strategy_decision", forbidden)
    monkeypatch.setattr(entrypoints, "assess_with_evidence", forbidden)
    result = _preflight(snapshot, monkeypatch)
    decisions = []
    for config in result["runtime_configs"]:
        context = StrategyContext(
            as_of=NOW,
            portfolio=PortfolioSnapshot(
                as_of=NOW, total_equity=100_000.0, buying_power=100_000.0,
                cash_balance=100_000.0, positions=(), metadata={"observed_effective_exposure": 0.0},
            ),
            market_data={"derived_indicators": {
                "SOXL": {"price": 80.0, "ma_trend": 75.0},
                "SOXX": {"price": 109.0, "ma_trend": 100.0, "realized_volatility_10": 0.20},
            }},
            runtime_config=config,
        )
        # This is the existing pure decision builder consumed by the promotion
        # runner's strategy entrypoint, not a replay, risk approval or order.
        decisions.append(entrypoints._build_soxl_soxx_trend_income_decision(context))
    assert [item.diagnostics["trend_entry_buffer"] for item in decisions] == [0.08, 0.10, 0.12]
    assert [item.diagnostics["base_blend_tier"] for item in decisions] == ["full", "mid", "mid"]


def test_learning_adapter_is_run_only_and_preserves_static_equity_descriptor(snapshot, monkeypatch):
    module = _module()
    admission = _preflight(snapshot, monkeypatch)
    runner = module.SoxlDevelopmentLearningRunner(
        json.loads((snapshot / "input.json").read_bytes()),
        admission["runtime_configs"][0],
        source_identity=admission["source_identity"],
        deadline=time.monotonic() + 30.0,
    )
    state = runner._initial_state()

    assert not isinstance(runner, PromotionBacktestRunner)
    assert not hasattr(runner, "run_purged_fold")
    assert not hasattr(runner, "run_locked_oos")
    assert runner._equity(state, runner._prices(0, "close")) == 100_000.0

    with pytest.raises(module.SoxlIsolatedResearchError, match="development_request_invalid"):
        runner.run(
            module._LEARNING_PROFILE,
            {
                "trend_entry_buffer": 0.08,
                "learning_only": True,
                "no_order": True,
                "mandate_id": "old-consumed-mandate",
            },
            start_date=datetime.fromisoformat(runner.sessions[0]["date"]).date(),
            end_date=module.DEVELOPMENT_END,
        )


@pytest.mark.parametrize(
    "mutation",
    [
        {"trend_entry_buffer": 0.121},
        {"managed_symbols": ()},
        {"old_mandate": "consumed"},
    ],
)
def test_learning_adapter_rejects_out_of_scope_runtime_config(snapshot, monkeypatch, mutation):
    module = _module()
    admission = _preflight(snapshot, monkeypatch)
    config = copy.deepcopy(admission["runtime_configs"][0])
    config.update(mutation)
    with pytest.raises(module.SoxlIsolatedResearchError, match="development_request_invalid"):
        module.SoxlDevelopmentLearningRunner(
            json.loads((snapshot / "input.json").read_bytes()),
            config,
            source_identity=admission["source_identity"],
            deadline=time.monotonic() + 30.0,
        )


@pytest.mark.parametrize(
    "targets",
    [
        {"SOXL": float("nan")},
        {"SOXL": 10**400},
        {"SOXL": 0.151},
        {"SOXL": 0.15, "BOXX": 0.051},
        {"UNKNOWN": 0.01},
    ],
)
def test_learning_simulated_risk_limits_fail_closed(targets):
    module = _module()
    with pytest.raises(module.SoxlIsolatedResearchError, match="development_risk_rejected"):
        module.SoxlDevelopmentLearningRunner._validated_targets(targets)


@pytest.mark.parametrize(
    ("scalars", "expected"),
    [
        ((0.5, 1.0, 1.0), {"SOXL": 0.05}),
        ((1.0, 0.5, 1.0), {"SOXL": 0.05}),
        ((1.0, 1.0, 0.5), {"SOXL": 0.05}),
    ],
)
def test_learning_applies_approve_scalars_before_returning_targets(
    snapshot, monkeypatch, scalars, expected
):
    module = _module()
    admission = _preflight(snapshot, monkeypatch)
    runner = module.SoxlDevelopmentLearningRunner(
        json.loads((snapshot / "input.json").read_bytes()),
        admission["runtime_configs"][0],
        source_identity=admission["source_identity"],
        deadline=time.monotonic() + 30.0,
    )
    runner._risk_engine.assess = lambda *_args, **_kwargs: RiskAction(
        action="approve",
        reason="bounded",
        budget_scalar=scalars[0],
        leverage_scalar=scalars[1],
        risk_asset_scalar=scalars[2],
    )
    state = runner._initial_state()

    assert runner._risk_sanity(0, state, {"SOXL": 0.10}, reason="test") == expected
    assert state.assessment_count == 1


@pytest.mark.parametrize(
    "scalar", [float("nan"), float("inf"), 10**400, -0.01, 1.01, True]
)
def test_learning_rejects_invalid_approve_scalars(snapshot, monkeypatch, scalar):
    module = _module()
    admission = _preflight(snapshot, monkeypatch)
    runner = module.SoxlDevelopmentLearningRunner(
        json.loads((snapshot / "input.json").read_bytes()),
        admission["runtime_configs"][0],
        source_identity=admission["source_identity"],
        deadline=time.monotonic() + 30.0,
    )
    runner._risk_engine.assess = lambda *_args, **_kwargs: RiskAction(
        action="approve", reason="invalid", budget_scalar=scalar
    )
    with pytest.raises(module.SoxlIsolatedResearchError, match="development_risk_rejected"):
        runner._risk_sanity(0, runner._initial_state(), {"SOXL": 0.10}, reason="test")


def test_learning_open_stop_uses_open_and_prior_regime_and_rejects_scaling(
    snapshot, monkeypatch
):
    module = _module()
    admission = _preflight(snapshot, monkeypatch)
    runner = module.SoxlDevelopmentLearningRunner(
        json.loads((snapshot / "input.json").read_bytes()),
        admission["runtime_configs"][0],
        source_identity=admission["source_identity"],
        deadline=time.monotonic() + 30.0,
    )
    observed = []

    def approve(_decision, portfolio, *, market_data):
        observed.append((portfolio.total_equity, market_data["market_regime"]))
        return RiskAction(action="approve", reason="bounded")

    runner._risk_engine.assess = approve
    state = runner._initial_state()
    state.quantities["SOXL"] = 1.0
    state.cash -= runner.sessions[1]["bars"]["SOXL"]["open"]
    runner._assess_control(
        1, state, {"SOXL": 0.1}, reason="executable_5pct_stop"
    )
    runner.sessions[1]["bars"]["SOXL"]["close"] *= 10
    runner.sessions[1]["market_regime"] = {"regime": "future-close-only"}
    runner._assess_control(
        1, state, {"SOXL": 0.1}, reason="executable_5pct_stop"
    )
    assert observed[0] == observed[1]
    assert observed[0][1] == runner.sessions[0]["market_regime"]

    runner._risk_engine.assess = lambda *_args, **_kwargs: RiskAction(
        action="approve", reason="shrink", budget_scalar=0.5
    )
    with pytest.raises(module.SoxlIsolatedResearchError, match="development_risk_rejected"):
        runner._assess_control(
            1, state, {"SOXL": 0.1}, reason="executable_5pct_stop"
        )


def _fake_window(cost_bps):
    result = BacktestResult(
        strategy_profile="fixture",
        domain="us_equity",
        param_set_id="fixture",
        params={},
        total_return=0.01,
        cagr=0.02,
        sharpe_ratio=0.3,
        sortino_ratio=0.4,
        max_drawdown=-0.05,
        oos_sharpe=0.3,
        oos_calmar=0.4,
        oos_max_drawdown=-0.05,
        walk_forward_stability=1.0,
    )
    return SimpleNamespace(
        result=result,
        turnover=1.0,
        costs_paid=cost_bps,
        trade_count=2,
        assessment_count=3,
    )


def test_development_rerun_binds_second_input_read_to_preflight_member_digest(
    snapshot, monkeypatch
):
    module = _module()
    original = module.preflight_soxl_isolated_research

    def replace_after_gate(*args, **kwargs):
        admission = original(*args, **kwargs)
        path = admission["input_path"]
        path.write_bytes(path.read_bytes() + b" ")
        path.chmod(0o600)
        return admission

    orchestrator = Mock(side_effect=AssertionError("orchestrator must not run"))
    monkeypatch.setattr(module, "preflight_soxl_isolated_research", replace_after_gate)
    monkeypatch.setattr(module.BacktestOrchestrator, "run", orchestrator)
    with pytest.raises(module.SoxlIsolatedResearchError, match="snapshot_invalid"):
        module.run_soxl_isolated_development(snapshot, **_arguments(snapshot))
    orchestrator.assert_not_called()


def test_development_preserves_completed_cost_when_second_cost_fails(snapshot, monkeypatch):
    module = _module()

    def replay(_self, _start, _end, cost_bps):
        if cost_bps == 10.0:
            raise module.SoxlIsolatedResearchError("private computation detail")
        return _fake_window(cost_bps)

    monkeypatch.setattr(module.SoxlDevelopmentLearningRunner, "_replay_window", replay)
    result = module.run_soxl_isolated_development(snapshot, **_arguments(snapshot))

    assert result["status"] == "development_incomplete"
    assert result["failure_reason"] == "development_trial_failed"
    assert result["trial_count_requested"] == 3
    assert result["trial_count_started"] == 1
    assert result["trial_count_completed"] == 0
    assert result["cost_scenario_count_started"] == 2
    assert result["cost_scenario_count_completed"] == 1
    assert result["real_backtest_executed"] is True
    assert result["trials"] == (
        {
            "status": "incomplete",
            "trend_entry_buffer": 0.08,
            "cost_scenarios": (
                {
                    "total_cost_bps": 5.0,
                    "total_return": 0.01,
                    "cagr": 0.02,
                    "sharpe_ratio": 0.3,
                    "sortino_ratio": 0.4,
                    "max_drawdown": -0.05,
                    "turnover": 1.0,
                    "costs_paid": 5.0,
                    "trade_count": 2,
                    "risk_assessment_count": 3,
                },
            ),
        },
    )


def test_development_uses_orchestrator_for_three_trials_without_disk_records(
    snapshot, monkeypatch
):
    module = _module()
    before = {path.name: path.read_bytes() for path in snapshot.iterdir()}
    calls = []
    original_run = module.BacktestOrchestrator.run

    def replay(_self, _start, _end, cost_bps):
        return _fake_window(cost_bps)

    def tracked_run(self, *args, **kwargs):
        result = original_run(self, *args, **kwargs)
        calls.append((args, kwargs, result))
        return result

    monkeypatch.setattr(module.SoxlDevelopmentLearningRunner, "_replay_window", replay)
    monkeypatch.setattr(module.BacktestOrchestrator, "run", tracked_run)
    result = module.run_soxl_isolated_development(snapshot, **_arguments(snapshot))

    assert result["status"] == "development_completed"
    assert result["failure_reason"] is None
    assert result["trial_count_started"] == result["trial_count_completed"] == 3
    assert result["cost_scenario_count_started"] == result["cost_scenario_count_completed"] == 9
    assert result["real_backtest_executed"] is True
    assert len(calls) == 3
    assert all(call[1]["end_date"] == module.DEVELOPMENT_END for call in calls)
    assert all(call[1]["params"]["learning_only"] is True for call in calls)
    assert all(call[2].oos_sharpe is None for call in calls)
    assert all(call[2].oos_calmar is None for call in calls)
    assert all(call[2].oos_max_drawdown is None for call in calls)
    assert all(call[2].walk_forward_stability is None for call in calls)
    assert before == {path.name: path.read_bytes() for path in snapshot.iterdir()}


def test_cli_development_output_contains_only_aggregates_and_learning_flags(
    monkeypatch, capsys
):
    import runpy
    import sys

    module = _module()
    result = {
        "status": "development_completed",
        "failure_reason": None,
        "trial_count_requested": 3,
        "trial_count_started": 3,
        "trial_count_completed": 3,
        "cost_scenario_count_started": 9,
        "cost_scenario_count_completed": 9,
        "trials": (),
        "window_class": "seen_development",
        "cost_scenarios_bps": (5.0, 10.0, 15.0),
        "loss_budget": 0.01,
        "stop_loss_distance": 0.05,
        "effective_exposure_cap": 0.50,
        "soxl_nominal_cap": 0.15,
        "account_drawdown_breaker": 0.10,
        "strategy_stop_breaker_count": 3,
        "learning_only": True,
        "promotion_eligible": False,
        "live_ready": False,
        "size_zero_required": True,
        "no_order": True,
        "real_backtest_executed": True,
    }
    monkeypatch.setattr(module, "run_soxl_isolated_development", lambda *args, **kwargs: result)
    script = Path(__file__).parents[1] / "scripts/preflight_soxl_isolated_research.py"
    monkeypatch.setattr(sys, "argv", [
        str(script), "--snapshot", "/not-read",
        "--package-sha256", "a" * 64,
        "--input-manifest-sha256", "b" * 64,
        "--run-development",
    ])
    with pytest.raises(SystemExit) as stopped:
        runpy.run_path(str(script), run_name="__main__")
    assert stopped.value.code == 0
    output = json.loads(capsys.readouterr().out)
    assert output == json.loads(json.dumps(result))
    assert not {"path", "date", "source_identity", "positions", "trades"} & set(output)


def test_actual_cli_emits_only_summary_and_never_runs_model_or_old_mandate(snapshot, monkeypatch, capsys):
    import runpy
    import sys
    from us_equity_snapshot_pipelines.lifecycle import soxl_acquisition_orchestration as old

    def forbidden(*_args, **_kwargs):
        raise AssertionError("old execution is forbidden")

    monkeypatch.setattr(old, "orchestrate_existing_soxl_snapshot", forbidden)
    monkeypatch.setattr(old, "run_soxl_promotion_research", forbidden)
    monkeypatch.setattr(old.ResearchMandateAuthorityGuard, "consume", forbidden)
    monkeypatch.setattr(_module(), "_now", lambda: NOW)
    args = _arguments(snapshot)
    script = Path(__file__).parents[1] / "scripts/preflight_soxl_isolated_research.py"
    monkeypatch.setattr(sys, "argv", [
        str(script), "--snapshot", str(snapshot),
        "--package-sha256", args["expected_package_sha256"],
        "--input-manifest-sha256", args["expected_input_manifest_sha256"],
    ])
    with pytest.raises(SystemExit) as stopped:
        runpy.run_path(str(script), run_name="__main__")
    assert stopped.value.code == 0
    output = json.loads(capsys.readouterr().out)
    assert output == {
        "status": "preflight_passed", "execution_provider": "codex", "trial_count": 3,
        "max_trials": 25, "learning_only": True, "promotion_eligible": False,
        "live_ready": False, "size_zero_required": True, "no_order": True, "real_backtest_executed": False,
    }


def test_cli_sanitizes_unknown_preflight_error_reason(monkeypatch, capsys):
    import runpy
    import sys

    module = _module()

    def broken(*_args, **_kwargs):
        raise module.SoxlIsolatedResearchError("private phase detail")

    monkeypatch.setattr(module, "preflight_soxl_isolated_research", broken)
    script = Path(__file__).parents[1] / "scripts/preflight_soxl_isolated_research.py"
    monkeypatch.setattr(sys, "argv", [
        str(script), "--snapshot", "/not-read",
        "--package-sha256", "a" * 64,
        "--input-manifest-sha256", "b" * 64,
    ])
    with pytest.raises(SystemExit) as stopped:
        runpy.run_path(str(script), run_name="__main__")
    assert stopped.value.code == 3
    assert json.loads(capsys.readouterr().out) == {
        "status": "unavailable",
        "reason": "snapshot_invalid",
    }
