from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
from typing import Any
import urllib.error

import scripts.post_codex_auto_merge_decision_comment as guard_comment
from scripts.post_codex_auto_merge_decision_comment import (
    append_label_actions_to_comment,
    build_guard_decision_comment,
    extract_monthly_issue_number,
    find_existing_guard_comment,
    guard_marker,
    list_issue_comments,
    sync_guard_decision_labels,
    upsert_guard_decision_comment,
)


def sample_pr() -> dict[str, Any]:
    return {
        "number": 12,
        "url": "https://github.com/QuantStrategyLab/UsEquitySnapshotPipelines/pull/12",
        "body": "<!-- codex-monthly-remediation:issue-34 -->\nGenerated by Codex.",
        "files": [
            {"path": "docs/operator_runbook.md"},
            {"path": "src/us_equity_snapshot_pipelines/contracts.py"},
        ],
    }


def sample_decision() -> dict[str, Any]:
    return {
        "should_merge": False,
        "reason": "blocked_files",
        "risk_level": "high",
        "review_decision": "APPROVED",
        "changed_lines": 42,
        "risk_reasons": ["blocked/high-risk files require human review"],
        "blocked_files": ["src/us_equity_snapshot_pipelines/contracts.py"],
        "medium_risk_files": [],
        "monthly_marker_prefix": "<!-- codex-monthly-remediation:issue-",
    }


def test_extract_monthly_issue_number_uses_decision_marker_prefix() -> None:
    pr = sample_pr()
    decision = {"monthly_marker_prefix": "<!-- custom-marker:issue-"}
    pr["body"] = "<!-- custom-marker:issue-77 -->"

    assert extract_monthly_issue_number(pr, decision) == 77
    assert extract_monthly_issue_number({"body": "no marker"}, decision) is None


def test_build_guard_decision_comment_includes_skip_reason_and_manual_next_action() -> None:
    body = build_guard_decision_comment(pr=sample_pr(), decision=sample_decision())

    assert body.startswith("<!-- codex-auto-merge-guard:pr-12 -->")
    assert "## Codex Auto-Merge Guard Decision" in body
    assert "- Reason: `blocked_files`" in body
    assert "- Risk level: `high`" in body
    assert "Treat this as a human-review item before merge." in body
    assert "`src/us_equity_snapshot_pipelines/contracts.py`" in body


def test_append_label_actions_to_comment_adds_visible_label_hygiene_section() -> None:
    body = append_label_actions_to_comment(
        "body\n",
        [
            "Removed stale auto-merge label `auto-merge-ok` from PR #12.",
            "Ensured human-review label `human-review-required` on PR #12.",
        ],
    )

    assert body == (
        "body\n\n"
        "### Label hygiene\n\n"
        "- Removed stale auto-merge label `auto-merge-ok` from PR #12.\n"
        "- Ensured human-review label `human-review-required` on PR #12.\n"
    )


def test_find_existing_guard_comment_matches_marker_prefix() -> None:
    assert (
        find_existing_guard_comment(
            [
                {"id": 1, "body": "ordinary"},
                {"id": 2, "body": f"{guard_marker(12)}\nbody"},
            ],
            guard_marker(12),
        )
        == 2
    )


def test_list_issue_comments_paginates_until_short_page() -> None:
    calls: list[str] = []

    def fake_request(method: str, url: str, token: str, payload=None):
        calls.append(url)
        if url.endswith("page=1"):
            return [{"id": i, "body": "x"} for i in range(100)]
        if url.endswith("page=2"):
            return [{"id": 101, "body": "y"}]
        raise AssertionError(url)

    comments = list_issue_comments(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        issue_number=34,
        request_fn=fake_request,
    )

    assert len(comments) == 101
    assert len(calls) == 2


def test_upsert_guard_decision_comment_updates_existing() -> None:
    calls: list[tuple[str, str, dict[str, str] | None]] = []

    def fake_request(method: str, url: str, token: str, payload=None):
        calls.append((method, url, payload))
        if method == "GET":
            return [{"id": 99, "body": f"{guard_marker(12)}\nold"}]
        if method == "PATCH":
            assert url.endswith("/issues/comments/99")
            assert payload == {"body": "new body"}
            return {"html_url": "https://github.local/comment/99"}
        raise AssertionError((method, url))

    action, url = upsert_guard_decision_comment(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        issue_number=34,
        body="new body",
        marker=guard_marker(12),
        request_fn=fake_request,
    )

    assert action == "updated"
    assert url == "https://github.local/comment/99"
    assert [method for method, _, _ in calls] == ["GET", "PATCH"]


def test_upsert_guard_decision_comment_creates_when_missing() -> None:
    calls: list[tuple[str, str, dict[str, str] | None]] = []

    def fake_request(method: str, url: str, token: str, payload=None):
        calls.append((method, url, payload))
        if method == "GET":
            return []
        if method == "POST":
            assert url.endswith("/issues/34/comments")
            assert payload == {"body": "new body"}
            return {"html_url": "https://github.local/comment/100"}
        raise AssertionError((method, url))

    action, url = upsert_guard_decision_comment(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        issue_number=34,
        body="new body",
        marker=guard_marker(12),
        request_fn=fake_request,
    )

    assert action == "created"
    assert url == "https://github.local/comment/100"
    assert [method for method, _, _ in calls] == ["GET", "POST"]


def test_sync_guard_decision_labels_removes_auto_merge_and_adds_human_review_for_high_risk() -> None:
    calls: list[tuple[str, str, dict[str, list[str]] | None]] = []
    decision = sample_decision() | {
        "auto_merge_label": "custom-auto-ok",
        "human_review_label": "custom-human-review",
    }

    def fake_request(method: str, url: str, token: str, payload=None):
        calls.append((method, url, payload))
        assert token == "token"
        if method == "DELETE":
            assert url.endswith("/issues/12/labels/custom-auto-ok")
            return None
        if method == "POST":
            assert url.endswith("/issues/12/labels")
            assert payload == {"labels": ["custom-human-review"]}
            return {"labels": [{"name": "custom-human-review"}]}
        raise AssertionError((method, url))

    actions = sync_guard_decision_labels(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        pr_number=12,
        decision=decision,
        request_fn=fake_request,
    )

    assert actions == [
        "Removed stale auto-merge label `custom-auto-ok` from PR #12.",
        "Ensured human-review label `custom-human-review` on PR #12.",
    ]
    assert [method for method, _, _ in calls] == ["DELETE", "POST"]


def test_sync_guard_decision_labels_ignores_missing_auto_merge_label_for_non_high_risk() -> None:
    calls: list[tuple[str, str, dict[str, list[str]] | None]] = []
    decision = sample_decision() | {"risk_level": "medium"}

    def fake_request(method: str, url: str, token: str, payload=None):
        calls.append((method, url, payload))
        if method == "DELETE":
            raise urllib.error.HTTPError(url, 404, "Not Found", hdrs=None, fp=None)
        raise AssertionError((method, url))

    actions = sync_guard_decision_labels(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        pr_number=12,
        decision=decision,
        request_fn=fake_request,
    )

    assert actions == ["Auto-merge label `auto-merge-ok` was already absent."]
    assert [method for method, _, _ in calls] == ["DELETE"]


def test_sync_guard_decision_labels_skips_when_policy_labels_match() -> None:
    def fail_if_called(method: str, url: str, token: str, payload=None):
        raise AssertionError("label sync should not call GitHub when labels collide")

    actions = sync_guard_decision_labels(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        pr_number=12,
        decision=sample_decision() | {
            "auto_merge_label": "same-label",
            "human_review_label": "same-label",
        },
        request_fn=fail_if_called,
    )

    assert actions == [
        "Skipped guard decision label sync because auto-merge and human-review labels are identical.",
    ]


def test_sync_guard_decision_labels_records_delete_failure_and_still_adds_human_review() -> None:
    calls: list[str] = []

    def fake_request(method: str, url: str, token: str, payload=None):
        calls.append(method)
        if method == "DELETE":
            raise urllib.error.HTTPError(url, 403, "Forbidden", hdrs=None, fp=None)
        if method == "POST":
            return {"labels": [{"name": "human-review-required"}]}
        raise AssertionError((method, url))

    actions = sync_guard_decision_labels(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        pr_number=12,
        decision=sample_decision(),
        request_fn=fake_request,
    )

    assert calls == ["DELETE", "POST"]
    assert actions == [
        "Could not remove stale auto-merge label `auto-merge-ok` from PR #12: HTTP 403.",
        "Ensured human-review label `human-review-required` on PR #12.",
    ]


def test_sync_guard_decision_labels_records_human_review_label_failure() -> None:
    calls: list[str] = []

    def fake_request(method: str, url: str, token: str, payload=None):
        calls.append(method)
        if method == "DELETE":
            return None
        if method == "POST":
            raise urllib.error.HTTPError(url, 403, "Forbidden", hdrs=None, fp=None)
        raise AssertionError((method, url))

    actions = sync_guard_decision_labels(
        api_url="https://api.github.local",
        repo="owner/repo",
        token="token",
        pr_number=12,
        decision=sample_decision(),
        request_fn=fake_request,
    )

    assert calls == ["DELETE", "POST"]
    assert actions == [
        "Removed stale auto-merge label `auto-merge-ok` from PR #12.",
        "Could not ensure human-review label `human-review-required` on PR #12: HTTP 403.",
    ]


def test_cli_updates_comment_with_label_hygiene_actions(tmp_path: Path, monkeypatch) -> None:
    pr_path = tmp_path / "pr.json"
    decision_path = tmp_path / "decision.json"
    output = tmp_path / "comment.md"
    pr_path.write_text(json.dumps(sample_pr()), encoding="utf-8")
    decision_path.write_text(json.dumps(sample_decision()), encoding="utf-8")
    calls: list[tuple[str, str, dict[str, Any] | None]] = []
    patched_comment_body = ""

    def fake_request(method: str, url: str, token: str, payload=None):
        nonlocal patched_comment_body
        calls.append((method, url, payload))
        assert token == "token"
        if method == "GET" and "/comments" in url:
            if len([item for item in calls if item[0] == "GET" and "/comments" in item[1]]) == 1:
                return []
            return [{"id": 99, "body": f"{guard_marker(12)}\nold"}]
        if method == "POST" and url.endswith("/issues/34/comments"):
            return {"html_url": "https://github.local/comment/99"}
        if method == "DELETE":
            return None
        if method == "POST" and url.endswith("/issues/12/labels"):
            return {"labels": [{"name": "human-review-required"}]}
        if method == "PATCH":
            patched_comment_body = payload["body"]
            return {"html_url": "https://github.local/comment/99"}
        raise AssertionError((method, url, payload))

    monkeypatch.setenv("GITHUB_TOKEN", "token")
    monkeypatch.setattr(guard_comment, "github_request", fake_request)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "post_codex_auto_merge_decision_comment.py",
            "--repo",
            "owner/repo",
            "--pr-json",
            str(pr_path),
            "--decision-json",
            str(decision_path),
            "--output-file",
            str(output),
            "--sync-labels",
            "--api-url",
            "https://api.github.local",
        ],
    )

    assert guard_comment.main() == 0
    assert "### Label hygiene" in patched_comment_body
    assert "Removed stale auto-merge label `auto-merge-ok`" in patched_comment_body
    assert "Ensured human-review label `human-review-required`" in patched_comment_body
    assert output.read_text(encoding="utf-8") == patched_comment_body


def test_cli_records_label_hygiene_comment_update_failure_in_output_file(tmp_path: Path, monkeypatch) -> None:
    pr_path = tmp_path / "pr.json"
    decision_path = tmp_path / "decision.json"
    output = tmp_path / "comment.md"
    pr_path.write_text(json.dumps(sample_pr()), encoding="utf-8")
    decision_path.write_text(json.dumps(sample_decision()), encoding="utf-8")
    comment_reads = 0

    def fake_request(method: str, url: str, token: str, payload=None):
        nonlocal comment_reads
        assert token == "token"
        if method == "GET" and "/comments" in url:
            comment_reads += 1
            if comment_reads == 2:
                raise urllib.error.HTTPError(url, 500, "Internal Server Error", hdrs=None, fp=None)
            return []
        if method == "POST" and url.endswith("/issues/34/comments"):
            return {"html_url": "https://github.local/comment/99"}
        if method == "DELETE":
            return None
        if method == "POST" and url.endswith("/issues/12/labels"):
            return {"labels": [{"name": "human-review-required"}]}
        raise AssertionError((method, url, payload))

    monkeypatch.setenv("GITHUB_TOKEN", "token")
    monkeypatch.setattr(guard_comment, "github_request", fake_request)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "post_codex_auto_merge_decision_comment.py",
            "--repo",
            "owner/repo",
            "--pr-json",
            str(pr_path),
            "--decision-json",
            str(decision_path),
            "--output-file",
            str(output),
            "--sync-labels",
            "--api-url",
            "https://api.github.local",
        ],
    )

    assert guard_comment.main() == 0
    body = output.read_text(encoding="utf-8")
    assert "### Label hygiene" in body
    assert "Removed stale auto-merge label `auto-merge-ok`" in body
    assert "Ensured human-review label `human-review-required`" in body
    assert "Could not update guard decision comment with label hygiene actions" in body


def test_cli_dry_run_writes_comment_body(tmp_path: Path) -> None:
    pr_path = tmp_path / "pr.json"
    decision_path = tmp_path / "decision.json"
    output = tmp_path / "comment.md"
    pr_path.write_text(json.dumps(sample_pr()), encoding="utf-8")
    decision_path.write_text(json.dumps(sample_decision()), encoding="utf-8")
    env = dict(os.environ)
    env.pop("GITHUB_TOKEN", None)

    result = subprocess.run(
        [
            sys.executable,
            "scripts/post_codex_auto_merge_decision_comment.py",
            "--repo",
            "QuantStrategyLab/UsEquitySnapshotPipelines",
            "--pr-json",
            str(pr_path),
            "--decision-json",
            str(decision_path),
            "--output-file",
            str(output),
            "--dry-run",
            "--sync-labels",
        ],
        cwd=Path(__file__).resolve().parents[1],
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert "guard_decision_comment_action=dry_run" in result.stdout
    assert output.read_text(encoding="utf-8").startswith("<!-- codex-auto-merge-guard:pr-12 -->")


def test_cli_skips_remote_comment_when_issue_marker_is_missing(tmp_path: Path) -> None:
    pr = sample_pr()
    pr["body"] = "no issue marker"
    pr_path = tmp_path / "pr.json"
    decision_path = tmp_path / "decision.json"
    output = tmp_path / "comment.md"
    pr_path.write_text(json.dumps(pr), encoding="utf-8")
    decision_path.write_text(json.dumps(sample_decision()), encoding="utf-8")

    result = subprocess.run(
        [
            sys.executable,
            "scripts/post_codex_auto_merge_decision_comment.py",
            "--repo",
            "QuantStrategyLab/UsEquitySnapshotPipelines",
            "--pr-json",
            str(pr_path),
            "--decision-json",
            str(decision_path),
            "--output-file",
            str(output),
        ],
        cwd=Path(__file__).resolve().parents[1],
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert "guard_decision_comment_action=skipped_missing_issue_marker" in result.stdout
    assert output.exists()
