"""Crisis response research from the shared QSP implementation.

USEQ retains its research CLI and import paths; the algorithm is maintained in
quant_strategy_plugins.crisis_response_research.
"""

from quant_strategy_plugins.crisis_response_research import (
    CRISIS_CONTEXT_MODES,
    CRISIS_CONTEXT_MODE_V1_RUBRIC,
    CRISIS_CONTEXT_MODE_V2_CONTEXT_PACK,
    DEFAULT_ROUTE_EXPECTATIONS,
    EXTERNAL_VALUATION_MODES,
    EXTERNAL_VALUATION_MODE_EXTERNAL_ONLY,
    EXTERNAL_VALUATION_MODE_OFF,
    EXTERNAL_VALUATION_MODE_PRICE_AND_EXTERNAL,
    EXTERNAL_VALUATION_MODE_PRICE_OR_EXTERNAL,
    FRAGILITY_CONTEXTS,
    FRAGILITY_CONTEXT_EXTERNAL_BREADTH_OR_QUALITY,
    FRAGILITY_CONTEXT_EXTERNAL_VALUATION,
    FRAGILITY_CONTEXT_VALUATION_BUBBLE,
    ROUTE_NO_ACTION,
    ROUTE_SYSTEMIC_STRESS_WATCH,
    ROUTE_TACO,
    ROUTE_TRUE_CRISIS,
    SEVERE_CRISIS_CONTEXTS,
    SEVERE_CRISIS_CONTEXT_EXTERNAL_VALUATION,
    SEVERE_CRISIS_CONTEXT_VALUATION_BUBBLE,
    build_event_response_decisions,
    build_route_audit_effectiveness_reports,
    main,
    run_crisis_response_research,
)

__all__ = ['CRISIS_CONTEXT_MODE_V1_RUBRIC', 'CRISIS_CONTEXT_MODE_V2_CONTEXT_PACK', 'CRISIS_CONTEXT_MODES', 'DEFAULT_ROUTE_EXPECTATIONS', 'EXTERNAL_VALUATION_MODE_EXTERNAL_ONLY', 'EXTERNAL_VALUATION_MODE_OFF', 'EXTERNAL_VALUATION_MODE_PRICE_AND_EXTERNAL', 'EXTERNAL_VALUATION_MODE_PRICE_OR_EXTERNAL', 'EXTERNAL_VALUATION_MODES', 'FRAGILITY_CONTEXT_EXTERNAL_BREADTH_OR_QUALITY', 'FRAGILITY_CONTEXT_EXTERNAL_VALUATION', 'FRAGILITY_CONTEXT_VALUATION_BUBBLE', 'FRAGILITY_CONTEXTS', 'ROUTE_NO_ACTION', 'ROUTE_SYSTEMIC_STRESS_WATCH', 'ROUTE_TACO', 'ROUTE_TRUE_CRISIS', 'SEVERE_CRISIS_CONTEXT_EXTERNAL_VALUATION', 'SEVERE_CRISIS_CONTEXT_VALUATION_BUBBLE', 'SEVERE_CRISIS_CONTEXTS', 'build_route_audit_effectiveness_reports', 'build_event_response_decisions', 'main', 'run_crisis_response_research']
