"""Crisis context research from the shared QSP implementation.

USEQ retains its research CLI and import paths; the algorithm is maintained in
quant_strategy_plugins.crisis_context_research.
"""

from quant_strategy_plugins.crisis_context_research import (
    CONTEXT_BOOL_COLUMNS,
    CONTEXT_LABEL_EXOGENOUS_POLICY_RESCUE,
    CONTEXT_LABEL_EXOGENOUS_SHOCK,
    CONTEXT_LABEL_FINANCIAL_CRISIS,
    CONTEXT_LABEL_NORMAL,
    CONTEXT_LABEL_POLICY_RESCUE,
    CONTEXT_LABEL_POLICY_SHOCK,
    CONTEXT_LABEL_RATE_BEAR,
    CONTEXT_LABEL_VALUATION_BUBBLE,
    DEFAULT_BUBBLE_PERSISTENCE_DAYS,
    DEFAULT_CRISIS_CONTEXT_EVENTS,
    EVENT_KIND_EXOGENOUS_SHOCK,
    EVENT_KIND_POLICY_RESCUE,
    EXTERNAL_VALUATION_MODES,
    EXTERNAL_VALUATION_MODE_EXTERNAL_ONLY,
    EXTERNAL_VALUATION_MODE_OFF,
    EXTERNAL_VALUATION_MODE_PRICE_AND_EXTERNAL,
    EXTERNAL_VALUATION_MODE_PRICE_OR_EXTERNAL,
    build_context_diagnostics,
    build_crisis_context_features,
    build_event_context_flags,
    build_external_breadth_quality_context,
    build_external_valuation_context,
    main,
)

__all__ = ['CONTEXT_BOOL_COLUMNS', 'CONTEXT_LABEL_EXOGENOUS_POLICY_RESCUE', 'CONTEXT_LABEL_EXOGENOUS_SHOCK', 'CONTEXT_LABEL_FINANCIAL_CRISIS', 'CONTEXT_LABEL_NORMAL', 'CONTEXT_LABEL_POLICY_RESCUE', 'CONTEXT_LABEL_POLICY_SHOCK', 'CONTEXT_LABEL_RATE_BEAR', 'CONTEXT_LABEL_VALUATION_BUBBLE', 'DEFAULT_BUBBLE_PERSISTENCE_DAYS', 'DEFAULT_CRISIS_CONTEXT_EVENTS', 'EXTERNAL_VALUATION_MODE_EXTERNAL_ONLY', 'EXTERNAL_VALUATION_MODE_OFF', 'EXTERNAL_VALUATION_MODE_PRICE_AND_EXTERNAL', 'EXTERNAL_VALUATION_MODE_PRICE_OR_EXTERNAL', 'EXTERNAL_VALUATION_MODES', 'EVENT_KIND_EXOGENOUS_SHOCK', 'EVENT_KIND_POLICY_RESCUE', 'build_context_diagnostics', 'build_crisis_context_features', 'build_event_context_flags', 'build_external_breadth_quality_context', 'build_external_valuation_context', 'main']
